// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Asp.net.Api.Date;

namespace School.Asp.net.Api.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("School.Asp.net.Api.Models.Class", b =>
                {
                    b.Property<int>("Classid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassCourse")
                        .HasColumnType("int");

                    b.Property<string>("ClassType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Classid");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("School.Asp.net.Api.Models.Pupil", b =>
                {
                    b.Property<int>("Pupilid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Classid")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pupilid");

                    b.HasIndex("Classid");

                    b.ToTable("Pupil");
                });

            modelBuilder.Entity("School.Asp.net.Api.Models.Pupil", b =>
                {
                    b.HasOne("School.Asp.net.Api.Models.Class", "Class")
                        .WithMany("Pupil")
                        .HasForeignKey("Classid");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("School.Asp.net.Api.Models.Class", b =>
                {
                    b.Navigation("Pupil");
                });
#pragma warning restore 612, 618
        }
    }
}
